import type { Metadata } from "next";
import Link from 'next/link';
// import { Geist, Geist_Mono } from "next/font/google"; // Removed Geist imports
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <header className="bg-gradient-to-r from-blue-100 to-white shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
            {/* 左侧 Logo */}
            <Link href="/" className="flex items-center space-x-2">
              <img src="/logo.svg" alt="Summarist.ai Logo" className="h-8" />
              <span className="text-2xl font-bold text-gray-800">booksummarizer.online</span>
            </Link>
            {/* 中间导航 */}
            <nav className="flex-1 flex justify-center">
              <div className="flex space-x-8">
                <Link href="/" className="text-gray-600 hover:text-blue-600 font-medium">Home</Link>
                <Link href="/categories" className="text-gray-600 hover:text-blue-600 font-medium">Categories</Link>
                <Link href="/favorites" className="text-gray-600 hover:text-blue-600 font-medium">Favorites</Link>
                <Link href="/" className="text-gray-600 hover:text-blue-600 font-medium">Search</Link>
              </div>
            </nav>
            {/* 右侧按钮 */}
            <div className="flex items-center space-x-4">
              <button className="px-4 py-1 rounded-md border border-blue-600 text-blue-600 hover:bg-blue-50 font-medium transition">Log in</button>
              <button className="px-4 py-1 rounded-md border border-gray-300 text-gray-700 hover:bg-gray-100 font-medium transition">Language</button>
            </div>
          </div>
        </header>
        {children}
        <footer className="bg-[#232b36] text-gray-200 py-8 mt-16">
          <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row items-center md:items-start justify-between">
            <div className="text-center md:text-left mb-4 md:mb-0">
              <div className="text-base">© 2025 booksummarizer.online. All rights reserved.</div>
              <div className="text-sm text-gray-400">AI-Powered Book Summaries</div>
            </div>
            <div className="flex space-x-6 text-base">
              <Link href="#" className="hover:underline">Privacy Policy</Link>
              <Link href="#" className="hover:underline">Contact</Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
